### ISSUE TITLE
deploy to a maven repository?

### ISSUE THREAD

**Issue by ambition-consulting** [OrhanKupusoglu/sloc-maven-plugin#2]
well done! it's a shame that such a nice plugin isn't available to everybody via maven repositories!

**Comment by ambition-consulting** [comment]
also, is there any way to summarise across multiple modules in a multi-module build?

**Comment by OrhanKupusoglu** [comment]
Greetings,
Thanks, I am glad that you have found this plugin useful.
Right after publishing these Java tools, I returned back to the C++, so they are in limbo now.
I am afraid that the summary you have described looks to be beyond the current capabilities of this tool.

**Comment by OrhanKupusoglu** [comment]
The request has been repeated with issue #5.
